# Generated by Django 4.0.1 on 2022-01-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personaje_user_extenduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajedetalle',
            name='personaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personaje_detalles', to='core.personaje'),
        ),
    ]
