# Generated by Django 4.0.1 on 2022-01-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_personajedetalle_personaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajedetalle',
            name='personaje',
        ),
        migrations.AddField(
            model_name='personaje',
            name='detalle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personajes_detalles', to='core.personajedetalle'),
            preserve_default=False,
        ),
    ]
